/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(physical_header_barker_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ece25f3ef365ce8c15eb9d9cb4af4a62)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hwu/physical_header_barker_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <physical_header_barker_tagged_stream_pydoc.h>

void bind_physical_header_barker_tagged_stream(py::module& m)
{

    using physical_header_barker_tagged_stream    = ::gr::hwu::physical_header_barker_tagged_stream;


    py::class_<physical_header_barker_tagged_stream, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<physical_header_barker_tagged_stream>>(m, "physical_header_barker_tagged_stream", D(physical_header_barker_tagged_stream))

        .def(py::init(&physical_header_barker_tagged_stream::make),
           py::arg("barker_len"),
           py::arg("add_tail"),
           py::arg("lengthtagname"),
           D(physical_header_barker_tagged_stream,make)
        )
        



        ;




}








